title: Trendy Science
description: Latest science research news explained clearly
url: https://www.sciencetrendy.com
baseurl: ""
markdown: kramdown
theme: minima

permalink: /news/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
